name: Build and deploy poster
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  build-and-deploy:
    name: 'Build and publish'
    runs-on: ubuntu-latest
    if: "github.repository == 'oleksandr-pavlyk/oneAPI-for-SciPy' && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: x64
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r ./requirements.txt
      - name: Build documentation
        run: |
          # warnings are errors
          sphinx-build -b html -WT --keep-going poster build -d doctrees
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'pull_request'}}
        with:
          name: html
          path: build/
          if-no-files-found: error
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[doc-deploy-bot]'
          git config --global user.email 'github-actions[doc-deploy-bot]@users.noreply.github.com'
      - name: Checkout gh-pages
        run: |
          git remote add tokened_docs https://oleksandr-pavlyk:${{ secrets.GITHUB_TOKEN }}@github.com/oleksandr-pavlyk/oneAPI-for-SciPy.git
          git fetch --all
          git checkout --track tokened_docs/gh-pages
      - name: Copy build artifact
        run: |
          rm -rf -v build && cp -R ./build/ .
      - name: Commit changes
        run: |
          git add . && git commit -m "Deploy: ${{ github.sha }}"
        continue-on-error: true
      - name: Push changes
        if: "success() && github.event_name != 'pull_request'"
        run: |
          git push tokened_docs gh-pages
